### ISSUE TITLE
EnforceBytecodeVersion add an option to not fail if jar file can't be read

### ISSUE THREAD

**Issue by hboutemy** [mojohaus/extra-enforcer-rules#10]
if a jar file can't be read, I suppose it can be considered as not having too high bytecode version, then should not make the rule fail
I suppose this can be discussed, so having an option would ideally be better

**Comment by Batmat** [comment]
I tend to disagree. I don't think silently ignoring bytecode issues is the
right path.

IMO, in this case it'd be better to just use the exclusion pattern for the
apparently tampered jars. And obviously, if the jars actually proove to be
correct bytecode then we just have to fix the code.

2015-09-04 8:15 GMT+02:00 Hervé Boutemy <notifications@github.com>:

> if a jar file can't be read, I suppose it can be considered as not having
> too high bytecode version, then should not make the rule fail
> I suppose this can be discussed, so having an option would ideally be
> better
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojohaus/extra-enforcer-rules/issues/10>.
>



-- 
Baptiste <Batmat> MATHUS - http://batmat.net
Sauvez un arbre,
Mangez un castor !

**Comment by hboutemy** [comment]
my case is https://builds.apache.org/view/M-R/view/Maven/job/maven-archetype-m3/192/console
I don't know why on this server one jar file cannot be read
but failing the build for that does not really help

**Comment by slachiewicz** [comment]
Fixed with bfbe8fa
