### ISSUE TITLE
BanDuplicateClasses Performance Issue

### ISSUE THREAD

**Issue by thomasnikolay** [mojohaus/extra-enforcer-rules#122]
We have a large Dependency with some big dependencies. The check for BanDuplicateClasses tooks over 10 minutes. The check consume the most time in https://github.com/mojohaus/extra-enforcer-rules/blob/149c131186bcfa8fc5d7ec496409affcc17e0059/src/main/java/org/apache/maven/plugins/enforcer/Hasher.java#L101 to extract the file from the JAR for generating the hash value.

![image](https://user-images.githubusercontent.com/2331287/102453387-6a442b80-403c-11eb-927e-77913450a42d.png)

Is it possible to optimize this behavior? I think to cache the JAR could help instead of to read the JAR for each file again.

**Comment by slawekjaranowski** [comment]
@thomasnikolay if you can - please check rule code from PR on your project, should be better.
