### ISSUE TITLE
banDuplicateClasses NPE when using ignored dependency config

### ISSUE THREAD

**Issue by KGHawes-DeLess** [mojohaus/extra-enforcer-rules#127]
Config based on the example at https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html
I also noticed that the second dependency in my config (slf4j) wasn't in the list of ignorable dependencies which appears just before the Reactor Summary.

I have a couple of dependencies that were built with the shade plugin so I can't just use the exclusion feature in the normal dependency config and this seemed like a great alternative to suppress that warning.

**My POM plugin config:**

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.0.0-M3</version>
				<executions>
					<execution>
						<id>default-cli</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireMavenVersion>
									<version>3.6.1</version>
								</requireMavenVersion>
								<requireJavaVersion>
									<version>1.8</version>
								</requireJavaVersion>
								
								<banDuplicateClasses>

									<dependencies>
										<dependency>
											<groupId>xml-apis</groupId>
											<artifactId>xml-apis</artifactId>
											<type>*ar</type>
										</dependency>
 										<dependency>
											<groupId>org.slf4j</groupId>
											<artifactId>slf4j-api</artifactId>
											<type>*ar</type>
										</dependency>
									</dependencies>
				 									
									<scopes>
										<scope>compile</scope>
										<scope>provided</scope>
									</scopes>
									<findAllDuplicates>true</findAllDuplicates>
									<ignoreWhenIdentical>true</ignoreWhenIdentical>
		
								</banDuplicateClasses>
								
							</rules>
							<fail>false</fail>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>extra-enforcer-rules</artifactId>
						<version>1.3</version>
					</dependency>
					<dependency>
						<groupId>org.sonatype.ossindex.maven</groupId>
						<artifactId>ossindex-maven-enforcer-rules</artifactId>
						<version>3.1.0</version>
					</dependency>
				</dependencies>
			</plugin>

**Maven Debug Output:**

[DEBUG] Configuring mojo org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce' with basic configurator -->
[DEBUG]   (f) commandLineRules = []
[DEBUG]   (s) fail = false
[DEBUG]   (s) failFast = false
[DEBUG]   (f) ignoreCache = false
[DEBUG]   (f) mojoExecution = org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce {execution: default-cli}
[DEBUG]   (s) project = MavenProject: my.foo:CIPDX:0.0.1-SNAPSHOT @ /home/chrdel/DEVELOPMENT/git/RoboDX/CIP_Engine/pom.xml
[DEBUG]   (s) version = 3.6.1
[DEBUG]   (s) version = 1.8
[DEBUG]   (s) groupId = xml-apis
[DEBUG]   (s) artifactId = xml-apis
[DEBUG]   (s) type = \*ar
[DEBUG]   (s) groupId = org.slf4j
[DEBUG]   (s) artifactId = slf4j-api
[DEBUG]   (s) type = \*ar
[DEBUG]   (f) dependencies = [xml-apis:xml-apis:\*ar, org.slf4j:slf4j-api:\*ar]
[DEBUG]   (f) scopes = [compile, provided]
[DEBUG]   (f) findAllDuplicates = true
[DEBUG]   (f) ignoreWhenIdentical = true
[DEBUG]   (s) rules = [org.apache.maven.plugins.enforcer.RequireMavenVersion@7692cd34, org.apache.maven.plugins.enforcer.RequireJavaVersion@33aa93c, org.apache.maven.plugins.enforcer.BanDuplicateClasses@32c0915e]
[DEBUG]   (s) session = org.apache.maven.execution.MavenSession@106faf11
[DEBUG]   (s) skip = false
[DEBUG] -- end configuration --
[DEBUG] Executing rule: org.apache.maven.plugins.enforcer.RequireMavenVersion
[DEBUG] Rule org.apache.maven.plugins.enforcer.RequireMavenVersion is cacheable.
[DEBUG] Detected Maven Version: 3.6.1
[DEBUG] Detected Maven Version: 3.6.1 is allowed in the range 3.6.1.
[DEBUG] Executing rule: org.apache.maven.plugins.enforcer.RequireJavaVersion
[DEBUG] Rule org.apache.maven.plugins.enforcer.RequireJavaVersion is cacheable.
[DEBUG] Detected Java String: '1.8.0_275'
[DEBUG] Normalized Java String: '1.8.0-275'
[DEBUG] Parsed Version: Major: 1 Minor: 8 Incremental: 0 Build: 275 Qualifier: null
[DEBUG] Detected JDK Version: 1.8.0-275 is allowed in the range 1.8.
[DEBUG] Executing rule: org.apache.maven.plugins.enforcer.BanDuplicateClasses
[DEBUG] Dependency tree resolution listener events:
[DEBUG] testArtifact: artifact=my.foo:CIPDX:pom:0.0.1-SNAPSHOT
[DEBUG] includeArtifact: artifact=my.foo:CIPDX:pom:0.0.1-SNAPSHOT
[DEBUG] startProcessChildren: artifact=my.foo:CIPDX:pom:0.0.1-SNAPSHOT
[DEBUG] endProcessChildren: artifact=my.foo:CIPDX:pom:0.0.1-SNAPSHOT
[INFO] Adding ignore: module-info
[DEBUG] Ignore: module-info maps to regex ^module-info(\.class)?$
[INFO] Adding ignore: META-INF/versions/\*/module-info
[DEBUG] Ignore: META-INF/versions/\*/module-info maps to regex ^META-INF/versions/.*/module-info(\.class)?$
[INFO] Adding ignorable dependency: xml-apis:xml-apis:\*ar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for CIPDX 0.0.1-SNAPSHOT:
[INFO] 
[INFO] CIPDX .............................................. FAILURE [  0.854 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.205 s
[INFO] Finished at: 2021-03-22T16:34:51-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (default-cli) on project CIPDX: Execution default-cli of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (default-cli) on project CIPDX: Execution default-cli of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)

**Comment by s13o** [comment]
There  is just a lack of documentation
Check sources, please. The `ignoreClasses` attribute is implicitly required.
A correct example is
```
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-enforcer-plugin</artifactId>
					<version>${maven-enforcer-plugin.version}</version>
					<executions>
						<execution>
							<id>enforce-ban-duplicate-classes</id>
							<goals>
								<goal>enforce</goal>
							</goals>
							<configuration>
								<rules>
									<banDuplicateClasses>
										<scopes>
											<scope>compile</scope>
										</scopes>
										<findAllDuplicates>true</findAllDuplicates>
										<ignoreWhenIdentical>true</ignoreWhenIdentical>
										<!-- a list of dependencies for which you want to ignore specific classes -->
										<dependencies>
											<dependency>
												<groupId>org.springframework</groupId>
												<artifactId>spring-jcl</artifactId>
												<ignoreClasses>org.apache.commons.logging.*</ignoreClasses>
											</dependency>
										</dependencies>
									</banDuplicateClasses>
								</rules>
								<fail>true</fail>
							</configuration>
						</execution>
					</executions>
					<dependencies>
						<dependency>
							<groupId>org.codehaus.mojo</groupId>
							<artifactId>extra-enforcer-rules</artifactId>
							<version>${extra-enforcer-rules.version}</version>
						</dependency>
					</dependencies>
				</plugin>
```
