### ISSUE TITLE
compiled for 1.5 to 1.15 but perhaps since max version 11 on enforcer, it disslikes?

### ISSUE THREAD

**Issue by burranb** [mojohaus/extra-enforcer-rules#128]
<dependency>
		    <groupId>com.ibm.mq</groupId>
		    <artifactId>com.ibm.mq.allclient</artifactId>
		    <version>9.2.0.2</version>
		</dependency>
contains subartifact org.bouncycastle:bcprov-jdk15on

Fail, NullPointerException due to BadVersion....solved by excluding 

				<execution>
						<id>enforce-bytecode-version</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<enforceBytecodeVersion>
									<message>Dependency compiled with a higher jdk version then TT targeted (${tt.targetJdk})</message>
									<maxJdkVersion>${tt.maxJdk.version}</maxJdkVersion>
									<excludes>
										<exclude>org.bouncycastle:bcprov-jdk15on</exclude>
									</excludes>
								</enforceBytecodeVersion>
							</rules>
							<fail>true</fail>
						</configuration>
					</execution>

tt.targetJdk and tt.maxJdk.version set to 11.

BUT should enforce rule really complain (and throw NullPointer) since org.bouncycastle:bcprov-jdk15on is compiled for 1.5 to 15?

**Comment by slachiewicz** [comment]
Could you add stack trace with NPE or minimal project to reproduce?
