### ISSUE TITLE
failing under enforcer v3.0.0

### ISSUE THREAD

**Issue by delanym** [mojohaus/extra-enforcer-rules#132]
The rules banCircularDependencies and banDuplicateClasses are failing under the new enforcer v3.0.0

` Unable to parse configuration of mojo org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce for parameter banDuplicateClasses: Cannot create instance of class org.apache.maven.plugins.enforcer.BanDuplicateClasses: org/apache/maven/shared/dependency/tree/DependencyTreeBuilderException: org.apache.maven.shared.dependency.tree.DependencyTreeBuilderException`

**Comment by slachiewicz** [comment]
please try workaround from here: https://github.com/mojohaus/extra-enforcer-rules/issues/131#issuecomment-890329715

**Comment by slachiewicz** [comment]
will be fixed with 1.4
