### ISSUE TITLE
Version 1.4 on maven central?

### ISSUE THREAD

**Issue by Dichotomia** [mojohaus/extra-enforcer-rules#143]
Hi there,

The version 1.4 has been tagged on github. But i can't see it on maven central?

Do you know why?

Regards

**Comment by slawekjaranowski** [comment]
Is waiting for voting
https://groups.google.com/g/mojohaus-dev/c/lN8roou3wD4

**Comment by Dichotomia** [comment]
Ok thanks. I didn't know the release process.
