### ISSUE TITLE
turn off debug logging

### ISSUE THREAD

**Issue by delanym** [mojohaus/extra-enforcer-rules#182]
When i include `<banDuplicateClasses>` I get an extra 2 lines in the logs

```
[INFO] Adding ignore: module-info
[INFO] Adding ignore: META-INF/versions/*/module-info
```

This is debug log - there is no module-info file written to disk.

**Comment by slawekjaranowski** [comment]
PR are welcome, looks easy

**Comment by thomasnikolay** [comment]
for the information purposes I mentioned in #247 also all ignores

`[INFO] Adding ignore: org.xml.*
[INFO] Adding ignore: org.objectweb.*
[INFO] Adding ignore: org.apache.*
[INFO] Adding ignore: org.firebirdsql.*
[INFO] Adding ignore: org.mozilla.*
[INFO] Adding ignore: org.krysalis.barcode4j.*
[INFO] Adding ignore: org.aspectj.*
[INFO] Adding ignore: org.slf4j.*
[INFO] Adding ignore: com.altova.*
[INFO] Adding ignore: com.sun.*
[INFO] Adding ignore: sun.tools.*
[INFO] Adding ignore: com.sap.*`
