### ISSUE TITLE
«Enforce Bytecode Version» rule: Introduce Java 18 support

### ISSUE THREAD

**Issue by svbrunov** [mojohaus/extra-enforcer-rules#200]
Dear maintainers,

The «Enforce Bytecode Version» rule does not support Java 18.

Let's consider the following execution configuration:

```
<execution>
    <id>enforce-bytecode-version</id>
    <goals>
        <goal>enforce</goal>
    </goals>
    <configuration>
        <rules>
            <enforceBytecodeVersion>
                <maxJdkVersion>18</maxJdkVersion>
            </enforceBytecodeVersion>
        </rules>
    </configuration>
</execution>
```

The `org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce` goal fails with the following error message:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (enforce-bytecode-version) on project avito-data: Execution enforce-bytecode-version of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce failed: Unknown JDK version given. Should be something like "1.7", "8", "11", "12", "13", "14", "15", "16", "17" -> [Help 1]
```

Could you please introduce the Java 18 support for the «Enforce Bytecode Version» rule and afterwards release the new version of the plugin?

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by svbrunov** [comment]
Dear Slawomir Jaranowski (@slawekjaranowski),

Thank you for the update!

Could you please release the updated version?

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by slawekjaranowski** [comment]
I hope I will release in next two weeks.
