### ISSUE TITLE
"Adding Ignore: " log should be on debug level instead of info

### ISSUE THREAD

**Issue by thomasnikolay** [mojohaus/extra-enforcer-rules#247]
Currently the information which classes added to ignore list is not a information of the build it is more printing the configuration and this is debug. In a multi-module are all classes are logged for each child.

Example: We have a build with 123 modules and it 6000 lines logged that some classes are ignored without context.

My recommendation would to set the log level to debug.

**Comment by slawekjaranowski** [comment]
Is it not similar to: #182?

**Comment by thomasnikolay** [comment]
you are right :-)
