### ISSUE TITLE
requireEncoding fails for UTF-8 without BOM

### ISSUE THREAD

**Issue by bjpe** [mojohaus/extra-enforcer-rules#25]
Hi,

I tried to use the `requireEncoding` enforcer rule to ensure that our Java source files are encoded in UTF-8. IntelliJ saves the files in UTF-8 without an Byte Order Mark (BOM), since adding a BOM led to various problems. However, files with ASCII letters only are recognized as `ISO-8859-1` or `ISO-8859-2`.

I debugged the code and figured out that for a file encoded in UTF-8 w/o BOM containing the content

```
test
```

the `icu` package determines the following order of detected charsets and confidences:

```
ISO-8859-2: 60
ISO-8859-1: 60
UTF-8: 15
```

If I change the encoding to UTF-8 with BOM, it changes to:

```
UTF-8: 100
ISO-8859-1: 42
ISO-8859-2: 37
Big5: 10
GB18030: 10
Shift_JIS: 10
```

I suggest to change the encoding retrieval such that it accepts a declared encoding whenever it occurs somewhere in the list of the possible encodings, not only at the first position representing the most likely one.

**Comment by ptahchiev** [comment]
The implementation is totally wrong in my opinion. Given a `File` the plugin gets the stream, then  tries to **guess** what the encoding of the stream is. That stream is not the `File` itself. I don't know why it is implemented like this - but I have the exact same problem. File is saved as UTF-8, but then it is **detected** the content is ISO-8859-2
