### ISSUE TITLE
Question about requireSameVersion

### ISSUE THREAD

**Issue by blackat** [mojohaus/extra-enforcer-rules#264]
Hello,
I am using the `requireSameVersion` rule but it does not print, like the dependency convergence, where issues are.
There is just an error but via `mvn dependency:tree -Dverbose` I cannot see any conflict.

How does it suppose to work this rule?

Thanks in advance for the answers.

**Comment by slawekjaranowski** [comment]
`requireSameVersion` is a rule from m-enforcer-p not from extra-enforcer-rules
https://maven.apache.org/enforcer/enforcer-rules/index.html

Please report here https://issues.apache.org/jira/browse/MENFORCER

**Comment by blackat** [comment]
Thanks a lot @slawekjaranowski appreciated
