### ISSUE TITLE
acceptAsciiSubset is missing from the Require Encoding documentation

### ISSUE THREAD

**Issue by henrik242** [mojohaus/extra-enforcer-rules#270]
acceptAsciiSubset was [introduced in v1.3](https://github.com/mojohaus/extra-enforcer-rules/issues/48) but is missing from the [Require Encoding docs](https://www.mojohaus.org/extra-enforcer-rules/requireEncoding.html)

**Comment by slawekjaranowski** [comment]
PR are welcome with fix documentation
