### ISSUE TITLE
RequirePropertyDiverges evaluates in own context

### ISSUE THREAD

**Issue by delanym** [mojohaus/extra-enforcer-rules#282]
I have 2 projects, a "build configuration" project A, and a multi-module project B.
A includes maven-enforcer-plugin configuration with a rule

```xml
          <execution>
            <id>module</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <phase>validate</phase>
            <configuration>
              <fail>true</fail>
              <rules>
                <requirePropertyDiverges>
                  <property>project.description</property>
                </requirePropertyDiverges>
              </rules>
            </configuration>
          </execution>
```

B inherits from A, but they are completely separate projects. I always need to rebuild A before seeing the inherited effects in B.

I expect this rule to fail for any module in B without a description tag, or where the description is the same as the parent. I get no failures when I should (and logs show the rule fires for each module in B).

If I move the rule configuration from A to B I get failures.
I suspect the rule is not being "lazy" when it should. It seems to be evaluating in the context of the project it was built, and not the project it is run, if that makes sense.

_If someone can confirm this hunch it might lead to a fix, but I don't have time to create a reproducer at this point._

**Comment by delanym** [comment]
Perhaps this should be another issue, but the rule ignores sub-modules that lack the property in question altogether. This is surely a bug. The rule should evaluate the project model, not the file.

**Comment by piercemar** [comment]
Hello, 
The "reference" value used for the requirePropertyDiverges rule, is the one computed for the project that defined the rule.

So your project B would fail only if the "main" pom has no description (the rule is skipped for the defining project), but not for child modules.
For my own purpose, I use a modified version of requirePropertyDiverges that accepts an additional "reference" parameter that can take 3 values : DEFINING, PARENT or BASE.

* DEFINING being the current behaviour of using the project defining the rule as reference
* PARENT being the direct parent project if it exists
* BASE being the top-most local project of your multi-module reactor.

I'd happily contribute a PR if someone deems it a worthy addition.
