### ISSUE TITLE
Support for ignoredScopes for banDuplicateClasses

### ISSUE THREAD

**Issue by sudr** [mojohaus/extra-enforcer-rules#30]
It doesn't appear that the banDuplicateClasses supports the ability to ignore the check for specified dependency scopes.

This would be a handy feature when needing to ignore this check for test dependencies for example.

**Comment by khmarbaise** [comment]
Maybe I misunderstand a thing here but a scope makes only sense to jar files which means to dependencies but not to classes.

**Comment by bokken** [comment]
I think the suggestion/request is to be able to ignore analysis of classes
coming from jar dependencies of specific scope.

While I understand that technically, I cannot immediately think of a
usecase where duplicate classes, even from test dependencies, would not be
problematic.

**Comment by sudr** [comment]
Correct @bokken. The duplicate classes in test jar dependencies maybe problematic like you said. We ran into a few of these and it just struck me as something that should be easily ignored because we can't really do much these anyways.

**Comment by sebthom** [comment]
I would also like to see that option. I only want/need to ensure that compile dependencies of my projects (that would end up as transitive dependencies) in other projects don't contain duplicate classes and thus don't cause problems for other users.

**Comment by sebthom** [comment]
Looking at the source code, this enforcer rule already seems to support this, however in the other way around, i.e. you can specify scopes that are checked but not scopes that are ignored.
```xml
<rules>
   <banDuplicateClasses>
      <scopes>
         <scope>compile</scope>
         <scope>provided</scope>
      </scopes>
      <findAllDuplicates>true</findAllDuplicates>
   </banDuplicateClasses>
</rules>
```

The `scopes` property however is not documented on https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html only in the source code [BanDuplicateClasses.java#L76](https://github.com/mojohaus/extra-enforcer-rules/blob/master/src/main/java/org/apache/maven/plugins/enforcer/BanDuplicateClasses.java#L76) where it says:

```java
/*
 * Only verify dependencies with one of these scopes
 */
private List<String> scopes;
```

This property was added 7 years ago. The test case is here https://github.com/mojohaus/extra-enforcer-rules/blob/master/src/it/mojo-1799/pom.xml

**Comment by sudr** [comment]
Thanks. Looks like this would do the trick.
