### ISSUE TITLE
Fail to detect dependency with java 9 modules

### ISSUE THREAD

**Issue by chatellier** [mojohaus/extra-enforcer-rules#31]
Hi,

I'm using log4j dependency version 2.9.0 which add support for java 9 modules.

But enforcer rule detect it as a java 9 dependency, that is not totally true (could be, but can run on java 8 jvm).

This is the error i got:

```
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-bytecode-version) @ agrosyst-services ---
[INFO] Restricted to JDK 1.8 yet org.apache.logging.log4j:log4j-api:jar:2.9.0:runtime contains META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class targeted to 53.0
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
Found Banned Dependency: org.apache.logging.log4j:log4j-api:jar:2.9.0
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
```

**Comment by khmarbaise** [comment]
This looks like a multi version jar file which is currently not supported by extra-enforcer-rule...

**Comment by chatellier** [comment]
Is it possible to make a new release about it.
There is about 2 new opened issue about this problem.

**Comment by sanderino666** [comment]
I am facing the same problem when upgrading my project from Spring Boot 1 to 2 which has an underlying dependency to log4j-api 2.10.0. Would be great if a new release is created!

**Comment by chatellier** [comment]
up ?
