### ISSUE TITLE
asm-6.0 recognized as JDK 1.9

### ISSUE THREAD

**Issue by wuchenwang** [mojohaus/extra-enforcer-rules#33]
We have found some Java 9 compatibility issue with one of the rules below trying to uplift to asm-6.0 (Release Notes http://forge.ow2.org/forum/forum.php?forum_id=2576).

```
[INFO] Restricted to JDK 1.8 yet org.ow2.asm:asm-analysis:jar:6.0:compile contains module-info.class targeted to JDK 1.9
[WARNING] Rule 15: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
Found Banned Dependency: org.ow2.asm:asm-util:jar:6.0
Found Banned Dependency: org.ow2.asm:asm-tree:jar:6.0
Found Banned Dependency: org.ow2.asm:asm:jar:6.0
Found Banned Dependency: org.ow2.asm:asm-analysis:jar:6.0
```

 Looks to be also related to this known issue (https://github.com/mojohaus/extra-enforcer-rules/commit/43b63605b637adb84b4676a0ba6c0c44032a30c2)

Could asm-6.0 be added to an IT to verify is excluded or fixed?

Thanks

**Comment by JeneJasper** [comment]
Duplicates #35
