### ISSUE TITLE
Migrate to Maven 3+ Minimum

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/extra-enforcer-rules#43]
We should migrate the whole project to Maven 3.X minimum.

**Comment by KroArtem** [comment]
I wonder if it would happen anytime? 🙂

**Comment by Dichotomia** [comment]
Resolved with https://github.com/mojohaus/extra-enforcer-rules/commit/d380fe56a7317a237bbce5b94fbab7f4581d3d1b ?
