### ISSUE TITLE
Add oraclejdk9 for build on travis.

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/extra-enforcer-rules#44]

**Comment by batmat** [comment]
@khmarbaise seems like you fixed this?

I am considering a new release of extra-enforcer-rules. AFAICT, this issue was the last thing you tagged for 1.0-beta-7?

Do you want to include something else, or are you fine with me releasing?

Thank you!

**Comment by khmarbaise** [comment]
Go for it..please..

**Comment by batmat** [comment]
@khmarbaise ack. Just finished the staging process, voting email sent a few seconds ago. Thanks!

**Comment by andham** [comment]
Why is this one still open?

**Comment by mfriedenhagen** [comment]
I think I will close this. Currently 7, 8, 11 and latest-is-greatest will automatically be tested, see: https://github.com/mojohaus/extra-enforcer-rules/blob/149c131186bcfa8fc5d7ec496409affcc17e0059/.travis.yml#L8-L12
