### ISSUE TITLE
Still in beta?

### ISSUE THREAD

**Issue by mattnelson** [mojohaus/extra-enforcer-rules#45]
This project has been in beta for about 4 years. Do you still consider this project beta? Can a 1.0 release be made?

**Comment by khmarbaise** [comment]
I had this thought also several times...I think it's really time to leave beta ;-)

**Comment by slachiewicz** [comment]
I saw new tags for release 1.0 and 1,1 in git but not yet artifacts published to sonatype oss/central

**Comment by batmat** [comment]
@slachiewicz yeah, vote in progress on the mojohaus ML, already two +1. This can be closed.
