### ISSUE TITLE
Release beta-8

### ISSUE THREAD

**Issue by afrin216** [mojohaus/extra-enforcer-rules#47]
@khmarbaise 

Now that we have a fix for the Java9/ASM issue (Merged in https://github.com/mojohaus/extra-enforcer-rules/commit/73e8b4d4730d7c13027b1742f6c80d6d6fcffc15), a quick `beta-8` release would be much appreciated. 

Plus we can validate if this works before going to `1.0.0` release.

**Comment by mattnelson** [comment]
Looks like beta-8 and beta-9 are released but available on central yet.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.codehaus.mojo%22%20AND%20a%3A%22extra-enforcer-rules%22

**Comment by afrin216** [comment]
Thanks @khmarbaise for the releases
