### ISSUE TITLE
Encoding check fails when enforcing UTF-8 and the file is us-ascii

### ISSUE THREAD

**Issue by bjornpalmqvist** [mojohaus/extra-enforcer-rules#48]
The requireEncoding check fails when guessing on a file that is us-ascii and we like it to enforce UTF-8. The requireEncoding guesses ISO-8859-1 instead. We are running linux with locale se_SV.utf8.

**Comment by bjornpalmqvist** [comment]
What type of encoding's are desirable to be detected? It's hard to detect the difference between ISO-8859-1 and ISO-8859-2. But to say that this i probably in the ISO-8859 family is easier. What encoding's do you need to be able to enforce? If I get some examples, I could change the implementation to try to detect them as well.

**Comment by khmarbaise** [comment]
If you like to make a contribution please do not change formatting of the code...otherwise it's more or less impossible to understand the change...

**Comment by bjornpalmqvist** [comment]
Oh, sorry about that, do you have your formatting rules documented or as an eclipse formatter rule file?

**Comment by bjornpalmqvist** [comment]
I beleve I got the formatting correct now.

**Comment by bjornpalmqvist** [comment]
Have you looked at the new pull request? Is that something that you think could be useful for solving this issue? Please let me know if there is something that I could do to make it better.

**Comment by mfriedenhagen** [comment]
Looks to me your code was merged by me with 52017dd8ff5e9ed7356c4e8f4d52ba070a1ba03f (you are of course still mentioned as author) so I close this now.

**Comment by kl0ck** [comment]
Is this fix already released? I have the same issue, could not make it work. Any example of usage?

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.1.0</version> 
				<executions>
					<execution>
						<id>enforce-encoding</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireEncoding>
									<encoding>ISO-8859-1</encoding>
									<includes>src/main/java/**, src/test/java/**</includes>
								</requireEncoding>
								<requireEncoding>
									<encoding>UTF-8</encoding>
									<includes>src/main/resources/**, src/test/resources/**</includes>
								</requireEncoding>
							</rules>
							<fastFail>false</fastFail>
							<acceptAsciiSubset>true</acceptAsciiSubset>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>extra-enforcer-rules</artifactId>
						<version>1.6.1</version>
					</dependency>
				</dependencies>
			</plugin>
