### ISSUE TITLE
enforceBytecodeVersion - ignoring optional dependencies

### ISSUE THREAD

**Issue by sebthom** [mojohaus/extra-enforcer-rules#52]
It would be great to have an option to ignore optional dependencies.

**Comment by khmarbaise** [comment]
Maybe I misunderstand your issue? You can already define `<ignoredScopes>..</ignoredScopes>`...see the docs https://www.mojohaus.org/extra-enforcer-rules/enforceBytecodeVersion.html

```xml
<rules>
  <enforceBytecodeVersion>
    <maxJdkVersion>1.7</maxJdkVersion>
    <ignoredScopes>optional</ignoredScopes>
  </enforceBytecodeVersion>
</rules>

**Comment by sebthom** [comment]
Thanks for your quick answer! Unfortunately this doesn't seem to work. Probably because "optional" isn't a real [dependency scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope ) but a scope modifier as in:
```xml
<dependency>
    <groupId>net.bytebuddy</groupId>
    <artifactId>byte-buddy</artifactId>
    <version>1.8.11</version>
    <scope>compile</scope>
    <optional>true</optional>
</dependency>
```

**Comment by khmarbaise** [comment]
Ah sorry..misunderstanding on my side...

**Comment by sebthom** [comment]
Maybe an attribute for the ignoreScope tag can introduced. Something like `<ignoredScope with-optional="true">compile</ignoredScope>`

**Comment by khmarbaise** [comment]
attributes do not work in maven pom files...
But this looks like a logical `&&` between `ignoredScopes` and `optional`...so you have the use case say a dependency in scope compile which has optional:true and other dependencies in scope: test which have also optional:true ?
I think a simple solution in the first step would be having a boolean saying `ignoreOptional=true` to ignore all dependencies which have `optional:true`? WDYT ?

**Comment by sebthom** [comment]
I basically only want to check the bytecode version of non-optional compile dependencies. I don't care about other scopes. So for my use case I don't require a flag to control that per scope. Something like `<ignoreOptionalDependencies/>` would be sufficient.

**Comment by khmarbaise** [comment]
So it could look like this:
```xml
<rules>
  <enforceBytecodeVersion>
    <maxJdkVersion>1.7</maxJdkVersion>
    <ignoreOptional>true</ignoreOptional>
  </enforceBytecodeVersion>
</rules>
```

**Comment by sebthom** [comment]
I think a more specific name would be useful. In `ignoreOptional` it may be unclear to users what the term "optional" refers to. Also think it should be plural.
The meaning of `ignoreClasses` in contrast is pretty clear: Ignore one (or more) class files.

**Comment by khmarbaise** [comment]
Sure good point...so `ignoresOptional` ?

**Comment by sebthom** [comment]
Works for me.

**Comment by sebthom** [comment]
@khmarbaise any ETA for merge?
