### ISSUE TITLE
Publish site for 1.0-beta-9

### ISSUE THREAD

**Issue by bradcupit** [mojohaus/extra-enforcer-rules#59]
It looks like 1.0-beta-9 has been released (at least, it's been tagged and the jar [is in central](http://search.maven.org/#artifactdetails%7Corg.codehaus.mojo%7Cextra-enforcer-rules%7C1.0-beta-9%7Cjar)), but [the website](http://www.mojohaus.org/extra-enforcer-rules/index.html) still says 1.0-beta-7 in the upper right:

<img width="992" alt="extra_enforcer_rules_ _extra_enforcer_rules" src="https://user-images.githubusercontent.com/106213/42631384-13376718-85a8-11e8-9072-e37d56d4978f.png">

**Comment by bradcupit** [comment]
I know there were some small documentation changes in #50, which is part of 1.0-beta-9

**Comment by khmarbaise** [comment]
Hi site has been updated. Thanks for your hint...
