### ISSUE TITLE
ICU4j detects multiple possible charsets but only the first is checked

### ISSUE THREAD

**Issue by wumpz** [mojohaus/extra-enforcer-rules#77]
The logic behind requireEncoding seems broken. 

One specifies a required encoding. Because source code files may be represented correctly by different encodings (ISO-8859-1, UTF-8, ASCII) the check only for the first detected by ICU4J is
simply not enough.

https://github.com/mojohaus/extra-enforcer-rules/blob/04bfb54ccafb2b947ef3ced9b16a5063ac356075/src/main/java/org/apache/maven/plugins/enforcer/RequireEncoding.java#L138

The requiredEncoding should be returned if it is part of detector.detectAll().

**Comment by slachiewicz** [comment]
no longer valid due to 52017dd8ff5e9ed7356c4e8f4d52ba070a1ba03f

**Comment by kl0ck** [comment]
Is this fix already released? I have the same issue, could not make it work. Any example of usage?

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.1.0</version> 
				<executions>
					<execution>
						<id>enforce-encoding</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireEncoding>
									<encoding>ISO-8859-1</encoding>
									<includes>src/main/java/**, src/test/java/**</includes>
								</requireEncoding>
								<requireEncoding>
									<encoding>UTF-8</encoding>
									<includes>src/main/resources/**, src/test/resources/**</includes>
								</requireEncoding>
							</rules>
							<fastFail>false</fastFail>
							<acceptAsciiSubset>true</acceptAsciiSubset>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>extra-enforcer-rules</artifactId>
						<version>1.6.1</version>
					</dependency>
				</dependencies>
			</plugin>

**Comment by wumpz** [comment]
I had a similar problem and was pointed to: https://github.com/mojohaus/extra-enforcer-rules/pull/49#issuecomment-667869961

Try to put `<acceptAsciiSubset>true</acceptAsciiSubset>` within `requireEncoding`. Does this work?

**Comment by kl0ck** [comment]
> I had a similar problem and was pointed to: [#49 (comment)](https://github.com/mojohaus/extra-enforcer-rules/pull/49#issuecomment-667869961)
> 
> Try to put `<acceptAsciiSubset>true</acceptAsciiSubset>` within `requireEncoding`. Does this work?

Yes, I found it some days ago. _acceptAsciiSubset_ tag must be inside rules -> requireEncoding. 

Thanks for your answer!
