### ISSUE TITLE
Enforce Bytecode Version Rule does not support Java 13

### ISSUE THREAD

**Issue by LukasPrediger** [mojohaus/extra-enforcer-rules#80]
The enforce-bytecode rule does not currently support Java 13. When it is executed it returns an error:

`Execution enforce-bytecode-version of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed: Unknown JDK version given. Should be something like "1.7", "8", "11", "12" -> [Help 1]`

**Comment by batmat** [comment]
Hello @LukasPrediger, if you have some time to submit a PR, that would help.

It should easy to write and test, see how it's done in https://github.com/mojohaus/extra-enforcer-rules/blob/04bfb54ccafb2b947ef3ced9b16a5063ac356075/src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java#L95-L97

Thanks!
