### ISSUE TITLE
make requireEncoding validate encoding rather than detect encoding by ICU4J

### ISSUE THREAD

**Issue by wilx** [mojohaus/extra-enforcer-rules#82]
It seems that the `requireEncoding` rule is detecting ISO-8859-1 where my IDE happily detects UTF-8. It seems to me that instead of detecting encoding the rule should try to parse files with desired encoding and signal decoding failures instead.

(Moved from mojohaus/mojo-parent#50 to here.)

**Comment by slachiewicz** [comment]
probably no longer valid due to changes to parsing logic
