### ISSUE TITLE
improve EnforceBytecodeVersion "Error while reading jar file" message

### ISSUE THREAD

**Issue by hboutemy** [mojohaus/extra-enforcer-rules#9]
should at least tell which jar file caused this failure, and eventually the message of the cause

**Comment by Batmat** [comment]
Seems legit. I'll have a look if you want.

2015-09-04 8:13 GMT+02:00 Hervé Boutemy <notifications@github.com>:

> should at least tell which jar file caused this failure, and eventually
> the message of the cause
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojohaus/extra-enforcer-rules/issues/9>.
>



-- 
Baptiste <Batmat> MATHUS - http://batmat.net
Sauvez un arbre,
Mangez un castor !

**Comment by hboutemy** [comment]
if I can work on other topics, I'm interested :)
thank you
