### ISSUE TITLE
Add property to bypass rules

### ISSUE THREAD

**Issue by isaac-s** [mojohaus/extra-enforcer-rules#92]
Certain rules may take time to run (for example: `banDuplicateClasses`).
It'd be nice to have a property that, if defined, will bypass these rules.
(Each rule should have its own bypass property)

**Comment by isaac-s** [comment]
(Workaround: isolate time-consuming rules to separate executions, and use `<skip>true</skip>` in these executions' configurations)

**Comment by mfriedenhagen** [comment]
Hello @isaac-s, this should be implemented in the maven-enforcer-plugin ( https://maven.apache.org/enforcer/maven-enforcer-plugin/project-info.html ) and not for one single rule. Please discuss this at the users' list or open an issue at JIRA.

**Comment by mfriedenhagen** [comment]
Though I think using profiles is a very viable solution in this case.
