### ISSUE TITLE
site generation broken

### ISSUE THREAD

**Issue by mfriedenhagen** [mojohaus/extra-enforcer-rules#99]
* With 1.3 the parent was updated to `mojo-parent-50`.
* However, now rendering the site of `extra-enforcer-rules` leads to all kinds of error messages due to a missing cobertura dependency.

**Comment by mfriedenhagen** [comment]
I will wait for mojo-parent-60 to be released before proceeding, adding corbertura-dependencies seems overkill.

**Comment by KroArtem** [comment]
@hboutemy , I see that you've updated site, does that mean this issue is no more actual?

**Comment by hboutemy** [comment]
I had to cheat a little bit to publish the site for the release: honestly, when I built normally, it did not work

I did not test site generation from HEAD

**Comment by hboutemy** [comment]
just upgraded parent POM to 60, and as Mirko expected, it fixed site generation (on JDK 8, a little javadoc issue breaks JDK 11 site, but that's another story: PR welcome)
